---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-data-generator
  name: prometheus-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-data-generator
  template:
    metadata:
      labels:
        app: prometheus-data-generator
    spec:
      containers:
      - image: ghcr.io/js94x/prometheus-data-generator
        imagePullPolicy: IfNotPresent
        env:
        - name: PDG_CONFIG
          value: /pdg/config.yml
        name: prometheus-data-generator
        ports:
        - containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
      volumes:
      - name: config
        configMap:
          name: prometheus-data-generator
